
initdata();

function initdata() {
  if(!localStorage.teachers) {
    const teachers = [
      {
  "id": 1,
  "name": "Carlos Mestre",
  "email": "carlos@teacher.com",
  "password": "abcd",
  "incapacity": "não",
  "gender": "masculino",
  "dateOfBirth": "1992-06-26",
  "locality": "Lisboa",
  "diplomes": ["Licenciatura em Geografia"],
  "disciplines": ["geografia"],
  "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
  "classType": "online",
  "price": "10€/h",
  "points": 50,
  "priority": 2,
  "photo": "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 2,
      "name": "Ana Sousa",
      "email": "ana@teacher.com",
      "password": "4r-Y7_#,",
      "incapacity": "sim",
      "gender": "feminino",
      "dateOfBirth": "1981-03-09",
      "locality": "Aveiro",
      "diplomes": ["Licenciatura em Geologia"],
      "disciplines": ["geologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "13€/h",
      "points": 86,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 3,
      "name": "João Ribeiro",
      "email": "joão@teacher.com",
      "password": "K#rM5W9k!E",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1987-12-17",
      "locality": "Lisboa",
      "diplomes": ["Licenciatura em História"],
      "disciplines": ["história"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "16€/h",
      "points": 81,
      "priority": 2,
      "photo":"https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 4,
      "name": "Maria Costa",
      "email": "maria@teacher.com",
      "password": "vF}|m7G#c:",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1987-08-26",
      "locality": "Guimarães",
      "diplomes": ["Licenciatura em Geografia"],
      "disciplines": ["geografia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "23€/h",
      "points": 57,
      "priority": 2,
      "photo": "https://images.unsplash.com/photo-1592621385612-4d7129426394?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 5,
      "name": "Pedro Lima",
      "email": "pedro@teacher.com",
      "password": "K-y24S=#6",
      "incapacity": "sim",
      "gender": "masculino",
      "dateOfBirth": "1992-04-21",
      "locality": "Porto",
      "diplomes": ["Licenciatura em Física química"],
      "disciplines": ["física química"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "23€/h",
      "points": 71,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
   
    },
    {
      "id": 6,
      "name": "Rita Martins",
      "email": "rita@teacher.com",
      "password": "*z,Fbc68",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1980-06-11",
      "locality": "Porto",
      "diplomes": ["Licenciatura em Matemática"],
      "disciplines": ["matemática"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "23€/h",
      "points": 93,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 7,
      "name": "Bruno Nogueira",
      "email": "bruno@teacher.com",
      "password": "#;c5M7opv*",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1980-08-03",
      "locality": "Porto",
      "diplomes": ["Licenciatura em Matemática"],
      "disciplines": ["matemática"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "19€/h",
      "points": 50,
      "priority": 2,
      "photo":"https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 8,
      "name": "Inês Fernandes",
      "email": "inês@teacher.com",
      "password": "US]M5x-6",
      "incapacity": "sim",
      "gender": "feminino",
      "dateOfBirth": "1985-04-27",
      "locality": "Porto",
      "diplomes": ["Licenciatura em Inglês"],
      "disciplines": ["inglês"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "10€/h",
      "points": 90,
      "priority": 2,
      "photo": "https://images.unsplash.com/photo-1592621385612-4d7129426394?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 9,
      "name": "Miguel Pinto",
      "email": "miguel@teacher.com",
      "password": "f&pQv4&f8",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1982-05-27",
      "locality": "Viseu",
      "diplomes": ["Licenciatura em Geologia"],
      "disciplines": ["geologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "19€/h",
      "points": 58,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

    },
    {
      "id": 10,
      "name": "Sandra Lopes",
      "email": "sandra@teacher.com",
      "password": "{;r^ScNx1",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1982-02-17",
      "locality": "Coimbra",
      "diplomes": ["Licenciatura em Francês"],
      "disciplines": ["francês"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "15€/h",
      "points": 90,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 11,
      "name": "Hugo Almeida",
      "email": "hugo@teacher.com",
      "password": "12l]x}>Mc1",
      "incapacity": "sim",
      "gender": "masculino",
      "dateOfBirth": "1991-03-02",
      "locality": "Coimbra",
      "diplomes": ["Licenciatura em Física química"],
      "disciplines": ["física química"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "14€/h",
      "points": 72,
      "priority": 2,
      "photo":"https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 12,
      "name": "Carla Neves",
      "email": "carla@teacher.com",
      "password": "<Jl^Q5&G",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1991-11-14",
      "locality": "Coimbra",
      "diplomes": ["Licenciatura em Geologia"],
      "disciplines": ["geologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "14€/h",
      "points": 94,
      "priority": 2,
      "photo": "https://images.unsplash.com/photo-1592621385612-4d7129426394?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 13,
      "name": "Tiago Morais",
      "email": "tiago@teacher.com",
      "password": "_zfV9[!+(K",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1988-06-28",
      "locality": "Guimarães",
      "diplomes": ["Licenciatura em Português"],
      "disciplines": ["português"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "19€/h",
      "points": 76,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

    },
    {
      "id": 14,
      "name": "Paula Rocha",
      "email": "paula@teacher.com",
      "password": "O0/#SLfxp",
      "incapacity": "sim",
      "gender": "feminino",
      "dateOfBirth": "1993-08-06",
      "locality": "Lisboa",
      "diplomes": ["Licenciatura em Biologia"],
      "disciplines": ["biologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "18€/h",
      "points": 54,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 15,
      "name": "André Figueiredo",
      "email": "andré@teacher.com",
      "password": "4W_t-4U4",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1993-07-20",
      "locality": "Setúbal",
      "diplomes": ["Licenciatura em Geografia"],
      "disciplines": ["geografia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "18€/h",
      "points": 70,
      "priority": 2,
      "photo":"https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 16,
      "name": "Luciana Gomes",
      "email": "luciana@teacher.com",
      "password": "2>K1,U(x",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1991-06-20",
      "locality": "Faro",
      "diplomes": ["Licenciatura em História"],
      "disciplines": ["história"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "23€/h",
      "points": 60,
      "priority": 2,
      "photo": "https://images.unsplash.com/photo-1592621385612-4d7129426394?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 17,
      "name": "Ricardo Teixeira",
      "email": "ricardo@teacher.com",
      "password": "[4Y,G,Lwgj",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1995-03-21",
      "locality": "Leiria",
      "diplomes": ["Licenciatura em Biologia"],
      "disciplines": ["biologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "24€/h",
      "points": 55,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

    },
    {
      "id": 18,
      "name": "Helena Duarte",
      "email": "helena@teacher.com",
      "password": "vI5]dTdz;",
      "incapacity": "sim",
      "gender": "feminino",
      "dateOfBirth": "1993-06-24",
      "locality": "Guimarães",
      "diplomes": ["Licenciatura em Geologia"],
      "disciplines": ["geologia"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "15€/h",
      "points": 66,
      "priority": 2,
      "photo": "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 19,
      "name": "Diogo Barros",
      "email": "diogo@teacher.com",
      "password": "rac|3HCY:",
      "incapacity": "não",
      "gender": "masculino",
      "dateOfBirth": "1986-08-23",
      "locality": "Faro",
      "diplomes": ["Licenciatura em Matemática"],
      "disciplines": ["matemática"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "presencial",
      "price": "14€/h",
      "points": 65,
      "priority": 2,
      "photo":"https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 20,
      "name": "Teresa Marques",
      "email": "teresa@teacher.com",
      "password": "G0m?/7u(",
      "incapacity": "não",
      "gender": "feminino",
      "dateOfBirth": "1991-03-27",
      "locality": "Coimbra",
      "diplomes": ["Licenciatura em Matemática"],
      "disciplines": ["matemática"],
      "aboutMe": "Sou um professor dedicado e com paixão pelo ensino.",
      "classType": "online",
      "price": "11€/h",
      "points": 77,
      "priority": 2,
      "photo": "https://images.unsplash.com/photo-1592621385612-4d7129426394?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
    ];
    localStorage.setItem("teachers", JSON.stringify(teachers));
  }
  
  if(!localStorage.students) {
    const students = [
      {
        "id": 1,
        "name": "João Silva",
        "email": "joao@student.com",
        "password": "J0@siLva",
        "grade": "6º ano",
        "EEcontact": "912345678",
        "incapacity": "não",
        "gender": "masculino",
        "dateOfBirth": "2012-04-15",
        "locality": "Lisboa",
        "disciplines": ["matemática", "português"],
        "aboutMe": "Gosto de ler livros de aventura e jogar futebol.",
        "favourites": [],
        "points": 10,
        "priority": 1
      },
      {
        "id": 2,
        "name": "Ana Martins",
        "email": "ana@student.com",
        "password": "An@8mRtS",
        "grade": "8º ano",
        "EEcontact": "913456789",
        "incapacity": "não",
        "gender": "feminino",
        "dateOfBirth": "2010-07-22",
        "locality": "Porto",
        "disciplines": ["inglês", "ciências"],
        "aboutMe": "Adoro desenhar e aprender novas línguas.",
        "points": 15,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 3,
        "name": "Pedro Costa",
        "email": "pedro@student.com",
        "password": "P3dr0_C$",
        "grade": "9º ano",
        "EEcontact": "914567890",
        "incapacity": "sim",
        "gender": "masculino",
        "dateOfBirth": "2009-11-05",
        "locality": "Coimbra",
        "disciplines": ["história"],
        "aboutMe": "Sou curioso sobre história e tecnologia.",
        "points": 20,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 4,
        "name": "Beatriz Almeida",
        "email": "beatriz@student.com",
        "password": "B3@tr1zAl",
        "grade": "11º ano",
        "EEcontact": "915678901",
        "incapacity": "não",
        "gender": "feminino",
        "dateOfBirth": "2007-02-18",
        "locality": "Braga",
        "disciplines": ["biologia", "química"],
        "aboutMe": "Apaixonada por ciência e natureza.",
        "points": 25,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 5,
        "name": "Rui Gonçalves",
        "email": "rui@student.com",
        "password": "Ru1G0nc!",
        "grade": "7º ano",
        "EEcontact": "916789012",
        "incapacity": "não",
        "gender": "masculino",
        "dateOfBirth": "2011-09-30",
        "locality": "Setúbal",
        "disciplines": ["educação física"],
        "aboutMe": "Gosto muito de desporto e jogos de equipa.",
        "points": 5,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 6,
        "name": "Mariana Lopes",
        "email": "mariana@student.com",
        "password": "M@r1L0ps",
        "grade": "12º ano",
        "EEcontact": "917890123",
        "incapacity": "não",
        "gender": "feminino",
        "dateOfBirth": "2006-05-12",
        "locality": "Faro",
        "disciplines": ["matemática", "física"],
        "aboutMe": "Interesso-me por física e engenharia.",
        "points": 30,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 7,
        "name": "Tiago Fernandes",
        "email": "tiago@student.com",
        "password": "T!4g0FnD",
        "grade": "5º ano",
        "EEcontact": "918901234",
        "incapacity": "sim",
        "gender": "masculino",
        "dateOfBirth": "2013-01-25",
        "locality": "Leiria",
        "disciplines": ["português"],
        "aboutMe": "Sou muito criativo e gosto de escrever histórias.",
        "points": 8,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 8,
        "name": "Sofia Ribeiro",
        "email": "sofia@student.com",
        "password": "S0f!R1bR",
        "grade": "10º ano",
        "EEcontact": "919012345",
        "incapacity": "não",
        "gender": "feminino",
        "dateOfBirth": "2008-03-08",
        "locality": "Viseu",
        "disciplines": ["inglês", "geografia"],
        "aboutMe": "Adoro viajar e conhecer novos lugares.",
        "points": 18,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 9,
        "name": "Diogo Nunes",
        "email": "diogo@student.com",
        "password": "D!0g0Nun",
        "grade": "8º ano",
        "EEcontact": "920123456",
        "incapacity": "não",
        "gender": "masculino",
        "dateOfBirth": "2010-10-10",
        "locality": "Aveiro",
        "disciplines": ["ciências", "matemática"],
        "aboutMe": "Sou curioso e gosto de experiências científicas.",
        "points": 12,
        "priority": 1,
        "favourites": []
      },
      {
        "id": 10,
        "name": "Carolina Pinto",
        "email": "carolina@student.com",
        "password": "C@r0lPin",
        "grade": "9º ano",
        "EEcontact": "921234567",
        "incapacity": "sim",
        "gender": "feminino",
        "dateOfBirth": "2009-12-19",
        "locality": "Guimarães",
        "disciplines": ["história", "português"],
        "aboutMe": "Gosto de música e de ler poesia.",
        "points": 14,
        "priority": 1,
        "favourites": []
      }
    ];
    localStorage.setItem("students", JSON.stringify(students));
  }

  if(!localStorage.admins) {
    const admins = [
      {
        "id": 1,
        "name": "Admin Principal",
        "email": "admin1@teachme.com",
        "password": "P@ss9w0r",
        "priority": 3
      },
      {
        "id": 2,
        "name": "Admin Secundário",
        "email": "admin2@teachme.com",
        "password": "X2!mN4#z",
        "priority": 3
      }
    ];
    localStorage.setItem("admins", JSON.stringify(admins));
  }
}